---
#
# KEYSTONE JOBS
#
apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-init
spec:
  template:
    spec:
      restartPolicy: Never
      # NOTE(arnaud) using initContainer to run them sequentially
      initContainers:
      - name: keystone-db-sync
        image: arnaudmorin/openstack-keystone:yoga
        command: ["keystone-manage", "db_sync"]
        volumeMounts:
        - name: keystone-conf
          mountPath: /etc/keystone/keystone.conf
          subPath: keystone.conf
        - name: keystone-conf
          mountPath: /etc/keystone/fernet-keys/0
          subPath: "0"
        - name: keystone-conf
          mountPath: /etc/keystone/fernet-keys/1
          subPath: "1"
      - name: keystone-bootstrap
        image: arnaudmorin/openstack-keystone:yoga
        command: ["keystone-manage", "bootstrap", "--bootstrap-password", "{{ .Values.password }}", "--bootstrap-admin-url", "https://{{ .Values.domain }}/v3/", "--bootstrap-internal-url", "https://{{ .Values.domain }}/v3/", "--bootstrap-public-url", "https://{{ .Values.domain }}/v3/", "--bootstrap-region-id", "RegionOne"]
        volumeMounts:
        - name: keystone-conf
          mountPath: /etc/keystone/keystone.conf
          subPath: keystone.conf
        - name: keystone-conf
          mountPath: /etc/keystone/fernet-keys/0
          subPath: "0"
        - name: keystone-conf
          mountPath: /etc/keystone/fernet-keys/1
          subPath: "1"
      containers:
      - name: keystone-done
        image: arnaudmorin/openstack-keystone:yoga
        command: ["echo", "done"]
      volumes:
      - name: keystone-conf
        configMap:
          name: keystone-conf
